interface route {
    type header = tuple<string, list<u8>>;
    type body = list<u8>;

    enum method {
        get,
        post,
        put,
        delete,
    }

    record request {
        ty: method,
        uri: string,
        headers: list<header>,
        body: body,
    }

    record response {
        status-code: u16,
        headers: list<header>,
        body: body,
    }

    handle: async func(request: request) -> response;
    route-paths: func() -> list<tuple<method, string>>;
}
