package allay:plugin@0.1.0;

interface route {
    type error = tuple<u32, string>;
    type response = result<list<u8>, error>;
    enum method {
        get,
        post,
        put,
        delete,
        head,
    }

    handle-request: func(ty: method, url: string, body: option<list<u8>>) -> response;
}

world plugin {
    export route;
}
