interface route {
    type header = tuple<string, string>;
    type body = list<u8>;

    enum method {
        get,
        post,
        put,
        delete,
    }

    record request {
        ty: method,
        uri: string,
        headers: list<header>,
        body: option<body>,
    }

    record response {
        status-code: u16,
        headers: list<header>,
        body: option<body>,
    }

    handle: async func(request: request) -> response;
}
