name = "Allay"
description = "A simple static site generator in Rust"
version = "0.1.0"
repository = "https://github.com/PKUSoftwareEngineeringTeam/Allay"
issue = "https://github.com/PKUSoftwareEngineeringTeam/Allay/issues"

[content]
dir = "contents"

[publish]
dir = "public"

[statics]
dir = "static"

[shortcode]
dir = "shortcodes"

[theme]
dir = "themes"
[theme.default]
name = "Axolotl"
repository = "https://github.com/PKUSoftwareEngineeringTeam/Axolotl"
[theme.template]
dir = "templates"

[log]
dir = "logs"
